### ISSUE TITLE
[BUG] Error in CG implementation

### ISSUE THREAD

**Issue by HuyD24** [leopard-ai/betty#15]
https://github.com/leopard-ai/betty/blob/39457e1800e3dd3c8b50c30bc6b7bd9ef4a96148/betty/hypergradient/cg.py#L53

I think `p_new` should be calculated based on `r_new` instead of `r` here. In the Wikipedia version (https://en.wikipedia.org/wiki/Conjugate_gradient_method) the corresponding formula is $p_{k+1} = r_{k+1} + \beta_k p_k$ with $r_{k+1}$ corresponding to `r_new`.

**Comment by sangkeun00** [comment]
Hello @HuyD24,

Thanks for your interest and pointing out the error in my code. I think you are right, and thus I fixed the code to use `r_new` instead of `r`. When I ran several benchmarks with both `r` and `r_new`, I didn't experience any noticeable performance differences, and hope your experiments also didn't get affected by this bug. Let me know if you have other concerns.

Best,
Sang

**Comment by sangkeun00** [comment]
Closing the issue as the bug is fixed.
