### ISSUE TITLE
[Question] Code for the continued pretraining experiment

### ISSUE THREAD

**Issue by kykim0** [leopard-ai/betty#23]
Hello!

I was hoping to reproduce the continued pretraining experiment in the SAMA paper and was curious where I could find the code. The learning_by_ignoring example looks quite relevant, but the datasets use there seem different from the ones used in the experiment. Could you point me to the experiment code?

Thanks!

**Comment by sangkeun00** [comment]
Hello,

Thanks for your interest in our work. I have one clarification question:

learning_by_ignoring is actually tri-level optimization (instead of bi-level optimization), and it’s the example used in our previous paper on Betty (https://openreview.net/forum?id=LV_MeMS38Q9) instead of in our SAMA paper.

If you are interested in the second experiment of our SAMA paper, you can find the (old) code in the supplemental material for our NeurIPS submission (https://openreview.net/forum?id=Xazhn0JoNx¬eId=CKLtWwVzdz <https://openreview.net/forum?id=Xazhn0JoNx&noteId=CKLtWwVzdz>).

If you are interested in something else, please let me know.

Best,
Sang

**Comment by sangkeun00** [comment]
Hello,

Thanks for your interest in our work. I have one clarification question:

`learning_by_ignoring` is actually tri-level optimization (instead of bi-level optimization), and it’s the example used in our previous paper on [Betty](https://openreview.net/forum?id=LV_MeMS38Q9) instead of in our SAMA paper.

If you are interested in the second experiment of our SAMA paper, you can find the (old) code in the supplemental material for our [NeurIPS submission](https://openreview.net/forum?id=Xazhn0JoNx&noteId=CKLtWwVzdz).

If you are interested in something else, please let me know.

Best,
Sang

**Comment by kykim0** [comment]
Thank you for your quick response and the code pointer!
